package mapper;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.03.17 at 11:35:05 PM IST
//

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="map">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="header">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="row">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cell" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="restirctionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="min-lenght" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="max-length" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "map"
})
@XmlRootElement(name = "mappings")
public class Mappings {

    @XmlElement(required = true)
    protected Map map;

    /**
     * Gets the value of the map property.
     *
     * @return
     *     possible object is
     *     {@link Map }
     *
     */
    public Map getMap() {
        return map;
    }

    /**
     * Sets the value of the map property.
     *
     * @param value
     *     allowed object is
     *     {@link Map }
     *
     */
    public void setMap(Map value) {
        this.map = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="header">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="row">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cell" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="restirctionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="min-lenght" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="max-length" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "header",
            "row"
    })
    public static class Map {

        @XmlElement(required = true)
        protected Header header;
        @XmlElement(required = true)
        protected Row row;
        @XmlAttribute(name = "class")
        protected String clazz;

        /**
         * Gets the value of the header property.
         *
         * @return
         *     possible object is
         *     {@link Header }
         *
         */
        public Header getHeader() {
            return header;
        }

        /**
         * Sets the value of the header property.
         *
         * @param value
         *     allowed object is
         *     {@link Header }
         *
         */
        public void setHeader(Header value) {
            this.header = value;
        }

        /**
         * Gets the value of the row property.
         *
         * @return
         *     possible object is
         *     {@link Row }
         *
         */
        public Row getRow() {
            return row;
        }

        /**
         * Sets the value of the row property.
         *
         * @param value
         *     allowed object is
         *     {@link Row }
         *
         */
        public void setRow(Row value) {
            this.row = value;
        }

        /**
         * Gets the value of the clazz property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setClazz(String value) {
            this.clazz = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "name",
                "index"
        })
        public static class Header {

            @XmlElement(required = true)
            protected Object name;
            @XmlElement(required = true)
            protected Object index;

            /**
             * Gets the value of the name property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setName(Object value) {
                this.name = value;
            }

            /**
             * Gets the value of the index property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setIndex(Object value) {
                this.index = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cell" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="restirctionType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="min-lenght" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="max-length" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "cell"
        })
        public static class Row {

            @XmlElement(required = true)
            protected List<Cell> cell;

            /**
             * Gets the value of the cell property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the cell property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCell().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Cell }
             *
             *
             */
            public List<Cell> getCell() {
                if (cell == null) {
                    cell = new ArrayList<Cell>();
                }
                return this.cell;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="restirctionType" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="min-lenght" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="max-length" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Cell {

                @XmlAttribute(name = "index")
                protected Integer index;
                @XmlAttribute(name = "dataType")
                protected String dataType;
                @XmlAttribute(name = "restirctionType")
                protected String restirctionType;
                @XmlAttribute(name = "min-lenght")
                protected Integer minLenght;
                @XmlAttribute(name = "max-length")
                protected Integer maxLength;
                @XmlAttribute(name = "required")
                protected String required;
                @XmlAttribute(name = "targetField")
                protected String targetField;

                /**
                 * Gets the value of the index property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *
                 */
                public Integer getIndex() {
                    return index;
                }

                /**
                 * Sets the value of the index property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *
                 */
                public void setIndex(Integer value) {
                    this.index = value;
                }

                /**
                 * Gets the value of the dataType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDataType() {
                    return dataType;
                }

                /**
                 * Sets the value of the dataType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDataType(String value) {
                    this.dataType = value;
                }

                /**
                 * Gets the value of the restirctionType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRestirctionType() {
                    return restirctionType;
                }

                /**
                 * Sets the value of the restirctionType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRestirctionType(String value) {
                    this.restirctionType = value;
                }

                /**
                 * Gets the value of the minLenght property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *
                 */
                public Integer getMinLenght() {
                    return minLenght;
                }

                /**
                 * Sets the value of the minLenght property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *
                 */
                public void setMinLenght(Integer value) {
                    this.minLenght = value;
                }

                /**
                 * Gets the value of the maxLength property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *
                 */
                public Integer getMaxLength() {
                    return maxLength;
                }

                /**
                 * Sets the value of the maxLength property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *
                 */
                public void setMaxLength(Integer value) {
                    this.maxLength = value;
                }

                /**
                 * Gets the value of the required property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRequired() {
                    return required;
                }
                /**
                 * Sets the value of the required property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRequired(String value) {
                    this.required = value;
                }


                /**
                 * Sets the value of the targetField property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTargetField(String value) {
                    this.targetField = value;
                }

                /**
                 * Gets the value of the targetField property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTargetField() {
                    return targetField;
                }



            }

        }

    }

}

